.TH EMOTE 1
.SH NAME
emote \- start the daemon for lightweight emoji picker written in GTK3
.SH SYNOPSIS
.B emote
.SH DESCRIPTION
.B emote
After starting the daemon, open the emoji picker with the set keyboard shortcut (CTRL + ALT + E by default). Then, put the mouse in a text field and press an emoji. On Xorg, it will type. In Wayland, one has to paste the emoji first.

.SH COPYRIGHT
Copyright \(co  2020-2024
.IP
Tom J Watson

.SH AUTHOR
This manual page (and the Debian packaging) were written by Dexx Stexx <dchosen1uno@gmail.com>. Permission is granted to copy, distribute, and/or modify this document under the the terms of the GPL3.
