#!/bin/sh

if [ ! -d "$SNAP_USER_DATA/.config/autostart" ];
then
  mkdir -p $SNAP_USER_DATA/.config/autostart
  ln -sfnt $SNAP_USER_DATA/.config/autostart/ $SNAP/meta/gui/emote.desktop
fi

# Force Wayland sessions to use XWayland. Some parts of GTK such as the
# clipboard management do no yet work under wayland.
export GDK_BACKEND="x11"

exec "$@"
